### ISSUE TITLE
Required features in Jan. 2024

### ISSUE THREAD

**Issue by ZhihaoDU** [alibaba-damo-academy/FunCodec#10]
Hi, all. I'm collecting the required features which will be considered implementing in Jan. 2024. Please let me know your concern and feel free to comment below. Thanks. To make FunCodec better!

**Comment by duj12** [comment]
> Hi, all. I'm collecting the required features which will be considered implementing in Jan. 2024. Please let me know your concern and feel free to comment below. Thanks. To make FunCodec better!

Support Chinese.  Maybe use your 60k hour Mandarin speech data to train a LauraTTS model, and this will be a Paraformer-like TTS model in Chinese Community.

**Comment by ZhihaoDU** [comment]
Thanks for your suggestion. We are considering to train a data-scale-up model.

**Comment by ZhihaoDU** [comment]
> > Hi, all. I'm collecting the required features which will be considered implementing in Jan. 2024. Please let me know your concern and feel free to comment below. Thanks. To make FunCodec better!
> 
> Support Chinese. Maybe use your 60k hour Mandarin speech data to train a LauraTTS model, and this will be a Paraformer-like TTS model in Chinese Community.

Thanks for your suggestion. We are considering to train a data-scale-up model.

**Comment by didadida-r** [comment]
Support Chinese.
