### ISSUE TITLE
Can the `run.sh` support for the training of Chinese TTS model?

### ISSUE THREAD

**Issue by Dinxin** [alibaba-damo-academy/FunCodec#11]
Your README.md said that we can train from scratch using your `run.sh` script, can it support for Chinese?

**Comment by ZhihaoDU** [comment]
The `run.sh` in  the `egs/LibriTTS/text2speech_laura` directory is used to re-produce LauraTTS model on the LibriTTS (English) corpus. In this script, we use `g2p_en` to tokenize the text to phonemes. Therefore this script is not able to use on Chinese corpora directly. You can replace `g2p_en` with  Chinese g2p packages, such as `pypinyin`. After preprocessing the text and obtaining the dictionary, this script can be used to train on the Chinese corpora.
By the way, the Chinese synthesis model is under internal development and test. We may release it in the future.

**Comment by Dinxin** [comment]
When will your Chinese model be released approximately?
