### ISSUE TITLE
Release of CN TTS model

### ISSUE THREAD

**Issue by lucasjinreal** [alibaba-damo-academy/FunCodec#13]
Looks like LauraTTS have Chinese demo, will consider opensource the pretrained model?

**Comment by ZhihaoDU** [comment]
Currently, the released LauraTTS model is trained on the LibriTTS corpus. I think it is not able to synthesize Chinese directly. The Chinese synthesis model is under internal development and test. We may release it in the future.

**Comment by lucasjinreal** [comment]
@ZhihaoDU  https://lauragpt.github.io/ where does these Chinese synthesis come from?

**Comment by ZhihaoDU** [comment]
> @ZhihaoDU https://lauragpt.github.io/ where does these Chinese synthesis come from?

Chinese cases in this page are generated by LauraGPT rather than LauraTTS, despite they have a similar architecture but different training data. While current released LauraTTS model is trained on LibriTTS, LauraGPT is trained on Librispeech, LibriTTS, AiShell and Aishell-2 and etc.

**Comment by lucasjinreal** [comment]
Oh, then, I mean LauraGPT, English only model is useless for me.

**Comment by deyituo** [comment]
@lucasjinreal laoge, you are 666.

**Comment by lucasjinreal** [comment]
@deyituo  Big iron, don't know what u say.
