### ISSUE TITLE
funcodec finetune

### ISSUE THREAD

**Issue by HaiFengZeng** [alibaba-damo-academy/FunCodec#24]
how can we adapt training the codec for smaller dataset?

**Comment by ZhihaoDU** [comment]
> how can we adapt training the codec for smaller dataset?

You can refer the recipe `egs/LibriTTS/codec/run.sh` to prepare your own data and finetune the model on it. You can also use the pre-trained parameters as a initialization with `--init_param xxx/xxx/model.pth`
