### ISSUE TITLE
Low-complexity FreqCodec requires a lot of VRAM

### ISSUE THREAD

**Issue by lbehringer** [alibaba-damo-academy/FunCodec#29]
Hi again,

I'm currently trying to retrain FreqCodec models using the configurations released by you (audio_codec-freqcodec_magphase-en-libritts-16k-gr8nq32ds320-pytorch and audio_codec-freqcodec_magphase-en-libritts-16k-gr1nq32ds320-pytorch).
Using an A100 (40GB) GPU, I am able to train the larger model (4.50M params, 2.18 GFlops) without issues at batch size 32.
However, the smaller model (0.52M params, 0.34 GFlops) causes a Cuda OOM error at batch size 32 (and at 24). 

As far as I can tell, in terms of architecture differences, the smaller model uses more groups in the depthwise convolutions, 3 residual layers (instead of 1), and a dilation base of 3 (instead of 2). 
I thought depthwise convolutions with more groups would reduce the required memory rather than increase it. Is this a misconception, or do you have any idea what the reason for this could be?

**Comment by ZhihaoDU** [comment]
Sorry for the late response. If the number of residual layers is same, the smaller model should require less VRAM. However, the model have a larger number of residual layers, the situation would be different. Not that the number of residual layers would affect each block in the Encoder. Compare with the larger model (4.50M params, 2.18 GFlops), the total NN layers of the smaller model (0.52M params, 0.34 GFlops) will be enlarged 3 times. As a result, we need more VRAM to save intermediate hidden states for back-propagation. I think this is the reason why a larger model model can be trained but a smaller model can't.

**Comment by ZhihaoDU** [comment]
If only the smaller model matches the task on your hand, I recommend you use more GPUs or reduce the batch size (from 32 to 16) or reduce the `speech_max_length` (from 40800 to 20400).

**Comment by lbehringer** [comment]
Thanks for your insight! I reduced the batch size to 16 for now, which is sufficient for my current use case.
