### ISSUE TITLE
Bug in gpu device setting

### ISSUE THREAD

**Issue by NZqian** [alibaba-damo-academy/FunCodec#3]
https://github.com/alibaba-damo-academy/FunCodec/blob/9944f8157cc5ae01126b59eb4b79d34bdcb60983/funcodec/bin/codec_inference.py#L548C42-L548C42

if CUDA_VISIBLE_DEVICES is set to other than 0, calling torch.cuda.set_device would result in CUDA error: invalid device ordinal. Maybe remove this line or just call torch.cuda.set_device(0)

**Comment by ZhihaoDU** [comment]
Thanks for your report. Which version of pytorch did you use ? I have tested the script on pytorch 1.12 and doesn't report the error with the following command:

```shell
sh encoding_decoding.sh --stage 1 --bit_width 16000 --batch_size 16 --model_dir pretrained_models/xxx --wav_scp path/to/wav.scp --out_dir outputs/debug --gpu_devices 0,1,2,3
```
