### ISSUE TITLE
TKR?

### ISSUE THREAD

**Issue by a897456** [alibaba-damo-academy/FunCodec#32]
![image](https://github.com/alibaba-damo-academy/FunCodec/assets/28752526/ea26c112-2aad-4eab-a8ed-0b11c9aae60c)
The first row in this table, 400 200.... 50 TKR, I think is the sampling rate divided by the stride, and then multiplied by the token, right?
just like: 16000/320*8=400TKR,
I guess that the number of tokens in each of the first four rows in the table is the same, and they are [8,4,2,1] and the same sampling rate 16000.
But, in the last two lines: I wonder that you get the same TKR by changing the sampling rate? Or, by changing tokens?

**Comment by a897456** [comment]
![image](https://github.com/alibaba-damo-academy/FunCodec/assets/28752526/89febc4d-9486-4196-ac8b-9bfd0971c599)
![image](https://github.com/alibaba-damo-academy/FunCodec/assets/28752526/e78d426e-50b0-414d-8b1e-dc4ca9a1f14e)
![image](https://github.com/alibaba-damo-academy/FunCodec/assets/28752526/20e05b08-1d5c-4816-945a-a42da49bdea6)
From the first two tables, extrapolating to the third table, is there an error, why should the scores of 4.29 and 3.86, in the time domain of M1, not be in the frequency domain of M2 M3? 
Because I think the first two tables are frequency domain scores,  so the third table with the same score should also be frequency domain.

**Comment by lbehringer** [comment]
Hi,
I had similar questions as you.

The TKR is explained here: https://github.com/alibaba-damo-academy/FunCodec/issues/27
The models labeled "FunCodec"/"M1" are actually time-domain models and similar to Encodec (the differences are explained here: https://github.com/alibaba-damo-academy/FunCodec/issues/5).
As far as I understand, only the models labeled as "Mag,Angle"/"Mag,Phase" correspond to the FreqCodec (i.e. frequency domain) architecture.

**Comment by a897456** [comment]
> Hi, I had similar questions as you.
> 
> The TKR is explained here: #27 The models labeled "FunCodec"/"M1" are actually time-domain models and similar to Encodec (the differences are explained here: #5). As far as I understand, only the models labeled as "Mag,Angle"/"Mag,Phase" correspond to the FreqCodec (i.e. frequency domain) architecture.

Hi @lbehringer 
Thank you for your reply to help me understand this article
As far as I know:

1.  the tag in Figure 2 in the article: "The overall architecture of the `FunCodec` models." should be changed to ".... of the `FreqCodec` models"
2. This article proposes a new model in the time domain, `Funcodec` (with some modifications on soundstream and Encodec), and then a new model in the frequency domain, `FreqCodec` (with some modifications on FunCodec, such as adding domain transformations), right?

**Comment by ZhihaoDU** [comment]
> Hi, I had similar questions as you.
> 
> The TKR is explained here: #27 The models labeled "FunCodec"/"M1" are actually time-domain models and similar to Encodec (the differences are explained here: #5). As far as I understand, only the models labeled as "Mag,Angle"/"Mag,Phase" correspond to the FreqCodec (i.e. frequency domain) architecture.

Thanks for your helpful response.

**Comment by ZhihaoDU** [comment]
> > Hi, I had similar questions as you.
> > The TKR is explained here: #27 The models labeled "FunCodec"/"M1" are actually time-domain models and similar to Encodec (the differences are explained here: #5). As far as I understand, only the models labeled as "Mag,Angle"/"Mag,Phase" correspond to the FreqCodec (i.e. frequency domain) architecture.
> 
> Hi @lbehringer Thank you for your reply to help me understand this article As far as I know:
> 
> 1. the tag in Figure 2 in the article: "The overall architecture of the `FunCodec` models." should be changed to ".... of the `FreqCodec` models"
> 2. This article proposes a new model in the time domain, `Funcodec` (with some modifications on soundstream and Encodec), and then a new model in the frequency domain, `FreqCodec` (with some modifications on FunCodec, such as adding domain transformations), right?

The response of @lbehringer is really helpful, and your understanding is almost right. The Figure 2 is used to offer a universal framework of both time-domain and frequency-domain models in FunCodec, therefore the title is "The overall architecture of the `FunCodec` models." 

For item 2, your understanding is right.
