### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by a897456** [alibaba-damo-academy/FunCodec#33]
I didn't run run.h, directly run codec_train.py, because I wanted to know the architecture of the whole program. But I have this problem. Do you know the reason?

Traceback (most recent call last):
  File "E:\00\FunCodec-master\funcodec\bin\codec_train.py", line 48, in <module>
    main(args=args)
  File "E:\00\FunCodec-master\funcodec\bin\codec_train.py", line 23, in main
    GANSpeechCodecTask.main(args=args, cmd=cmd)
  File "E:\00\FunCodec-master\funcodec\tasks\abs_task.py", line 1130, in main
    cls.main_worker(args)
  File "E:\00\FunCodec-master\funcodec\tasks\abs_task.py", line 1239, in main_worker
    model = cls.build_model(args=args)
  File "E:\00\FunCodec-master\funcodec\tasks\gan_speech_codec.py", line 310, in build_model
    frontend = frontend_class(**args.frontend_conf)
TypeError: 'NoneType' object is not callable

**Comment by ZhihaoDU** [comment]
I think this error is due to the uncompleted configuration. I recommend you first run the run.sh, then the log file will be created automatically. Then, you can find the python command at the first line in  the log file. You can use this python command to learn the whole framework.

**Comment by a897456** [comment]
> I think this error is due to the uncompleted configuration. I recommend you first run the run.sh, then the log file will be created automatically. Then, you can find the python command at the first line in the log file. You can use this python command to learn the whole framework.

The reason why I don't run run.h is because it will download the dataset and it will take a long time.
In fact, there is already a dataset, I can copy it, so your run.h code can add a judgment: if there is a data set, don't download it. But I don't know how to edit this code, can you help me?

https://github.com/alibaba-damo-academy/FunCodec/blob/3435d870126a48fe61a87fac1af3b6530be388ea/egs/LibriTTS/codec/run.sh#L77-L88

**Comment by ZhihaoDU** [comment]
First, you should download, unzip and place the dataset as expect of the stage 0. Then, you can skip the download stage and start from stage 1 as follows:
`bash run.sh --stage 1 ....`

**Comment by a897456** [comment]
> First, you should download, unzip and place the dataset as expect of the stage 0. Then, you can skip the download stage and start from stage 1 as follows: `bash run.sh --stage 1 ....`

Wow, so easy, so cool, nice job.
