### ISSUE TITLE
Discriminator loss？

### ISSUE THREAD

**Issue by a897456** [alibaba-damo-academy/FunCodec#35]
![image](https://github.com/alibaba-damo-academy/FunCodec/assets/28752526/78eb4b4d-e039-4231-b359-e8525043c0a4)
As far as I know, should the loss in the figure above be the generator loss? What does the discriminator loss look like?

**Comment by ZhihaoDU** [comment]
The discriminator is adversarially trained to maximize the equation (5) in Page 3. 
For implement details, please refer to https://github.com/alibaba-damo-academy/FunCodec/blob/master/funcodec/models/codec_basic.py#L631-L653

**Comment by a897456** [comment]
> The discriminator is adversarially trained to maximize the equation (5) in Page 3. For implement details, please refer to https://github.com/alibaba-damo-academy/FunCodec/blob/master/funcodec/models/codec_basic.py#L631-L653

https://github.com/alibaba-damo-academy/FunCodec?tab=readme-ov-file#batch-inference
How can I get this folder: `input_wav.scp`?

**Comment by a897456** [comment]
![6ada5568ba2c6ef3a8ffc6e8b5d0e8d](https://github.com/alibaba-damo-academy/FunCodec/assets/28752526/7715f436-c310-4bdd-9852-bd818ffced5f)
I am using Windows, so run.sh keeps reporting errors and does not get ·input_wav.scp·. So is there a good way to run it on Windows?

**Comment by ZhihaoDU** [comment]
This repo has be only tested on linux, I haven't try it on windows. The sh script is written for Linux.

**Comment by a897456** [comment]
ok,thanks
