### ISSUE TITLE
run.sh: 34: utils/parse_options.sh: Syntax error: Bad for loop variable

### ISSUE THREAD

**Issue by voidpointz** [alibaba-damo-academy/FunCodec#39]
在text2speech_laura文件夹下，输入sh run.sh进行模型训练时，报了如题所示的错误，请问是还需要添加什么参数吗？还有下载的预训练模型audio_codec-encodec-zh_en-general-16k-nq32ds640-pytorch文件夹中的config: conf/encodec_lstm_16k_n32_600k_step_rmseg_use_power_ds640.yaml是在项目的哪里？在项目中没有找到，我想查看模型的结构进行修改，谢谢。

**Comment by Value-Jack** [comment]
想请问一下你最后是如何解决的，发现同样爆了这个错误
