### ISSUE TITLE
Model sometimes stops training due to nan inputs

### ISSUE THREAD

**Issue by hanshounsu** [alibaba-damo-academy/FunCodec#47]
The model sometimes prints out "got nan" on the log file, and gets exited during training.

Seems there has been nan values occurring rarely, in the Conv1d layers.

Can you provide any insights on how you resolved the issue..?

Thanks for the good work!

**Comment by ZhihaoDU** [comment]
please provide the following information:
1. which model
2. what kind of data
3. snapshot of errors
4. system information

**Comment by hanshounsu** [comment]
I assume this is due to my mistake. Thanks!

**Comment by UkiTenzai** [comment]
I met the same problem, especially when I set the channel=32, how to fix it?
