### ISSUE TITLE
Differences with encodec？

### ISSUE THREAD

**Issue by HeJinLing** [alibaba-damo-academy/FunCodec#5]
请问大佬，时域的funcodec和encodec区别在什么地方呢？

**Comment by ZhihaoDU** [comment]
Question: What's the difference between funcodec and encodec on time-domain models ?
Response: Thanks for your question. The differences are as follows:
1. We involve a power-spectrum loss to enhance the quality in middle frequency, as shown in the Table 3 of the paper https://arxiv.org/abs/2309.07405.
2. We provide low and normal frame-rate models trained both on LibriTTS and internal industrial datasets. As a result, our low frame-rate model achieves the SOTA ViSQOL scores on commonly-used datasets including AiShell, Librispeech, Wenet, giga speech and so on.
3. FunCodec as a toolkit provides full training and inference capacity, while Encodec only release a model and inference recipe.
4. FunCodec as a toolkit provides a super set of features than other open-source toolkits, including distributed training, batchified inference, more discriminators and frequency-domain models.

BTW. Codec based text-to-speech and music models will be released soon.
